version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: npm
    directory: '/cognito-admin/app/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cognito-admin-app:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/cognito-admin/infra/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cognito-admin-infra:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/cognito-trigger-examples/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cognito-trigger-examples:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/aws-console-signin-example/common/cognito-singin/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      common:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      root:
        patterns:
          - "*"
