version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directories:
      - '/'
      - '/cognito-admin/app/'
      - '/cognito-admin/infra/'
      - '/cognito-trigger-examples/'
      - '/aws-console-signin-example/common/cognito-singin/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      common:
        patterns:
          - "*"
