packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

legacyPeerDeps: true

nodeLinker: hoisted

overrides:
  '@aws-console-signin-example/common-cognito-singin': ./common/cognito-singin/
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'

shamefullyHoist: true

strictPeerDependencies: false

symlink: false
